name: vm
favicon: null
layout_spectrum: 0.45132609200663865
typography_spectrum: 0.48927827179431915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.717649022815749
  lightness: 0.11363597819581628
  saturation: 0.9860395274590701
  rhythmicContrast: 0.30015421472489834
purpose: []
