name: vm
favicon: null
layout_spectrum: 0.01267
typography_spectrum: 0.48902
title: VM London
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff1cf'
    - '#faba70'
    - '#19385d'
    - '#000000'
    - '#eb4323'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
